apiVersion: batch/v1
kind: Job
metadata:
  name: counter
spec:
  completions: 1
  parallelism: 1
  backofflimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - args:
        - /bin/sh
        - -c
        - ...
        image: nginix:1.24.0 
        name: counter
