apiVersion: batch/v1
kind: CronJob
metadata:
  name: current-date
spec:
  jobTemplate:
    metadata:
      name: current-date
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: nginx:1.21.6
            name: current-date
            command:
            - /bin/sh
            - -c
            - 'echo "Current date: $(date)"'
  schedule: '* * * * *'