apiVersion: batch/v1 
kind: Job 
metadata: 
  name: testjob 
spec: 
  template:
    spec: 
      restartPolicy: Never
      containers: 
        - image: ubuntu 
          name: container1 
          command: ["bin/bash","-c", "sudo apt update; sleep 30"] 
      